remaxjs/remax

- .yarnrc
- packages/@remax/cli/yarn.lock
- packages/@remax/components/yarn.lock
- packages/@remax/core/yarn.lock
- packages/@remax/demo/yarn.lock
- packages/@remax/weui/yarn.lock
- yarn.lock
- add .yarnrc file, set registry https://registry.npmjs.org/
- regenerate yarn.lock to fix `resolved` field
- fix all packages yarn.lock
> chore(yarn): add .yarnrc & fix yarn.lock resolved

- README.md
- package.json
- packages/@remax/babel-plugin-remax-static-info/package.json
- packages/@remax/components/package.json
- packages/@remax/core/package.json
- packages/@remax/demo/package.json
- packages/@remax/weui/package.json
- yarn.lock
- add “build” npm script
- improve run demo for the frist time
- update README.md(Quick start)
> chore: add npm build script & improve run demo for the frist time

- README.md
Add throughput from https://waffle.io/CodeFalling/remax/metrics/throughput
> add throughput graph

- packages/remax-cli/src/build/plugins/page.ts
- packages/remax-cli/src/build/rollupConfig.ts
> fix create page config babel plugin bug

- packages/remax-cli/package.json
- packages/remax-cli/src/build/rollupConfig.ts
- packages/remax-cli/src/getEntries.ts
- packages/remax-cli/typings/index.d.ts
- packages/remax-cli/yarn.lock
1. 把 app.json 加入 entries
2. 支持处理 json 文件
resolve #29 
resolve #26
> make rollup watch json

- packages/remax-cli/src/build/plugins/app.ts
> resolve conflict

- packages/remax-cli/src/build/adapters/alipay/index.ts
- packages/remax-cli/src/build/adapters/index.ts
- packages/remax-cli/src/build/adapters/wechat/hostComponents/button.ts
- packages/remax-cli/src/build/adapters/wechat/index.ts
- packages/remax-cli/src/build/plugins/removeConfig.ts
- packages/remax-cli/src/build/plugins/template.ts
- packages/remax-cli/src/build/rollupConfig.ts
- packages/remax-cli/src/getEntries.ts
- packages/remax-cli/src/readManifest.ts
> use config.js to create manifest

- packages/remax/src/adapters/alipay/components/index.ts
- packages/remax/src/adapters/wechat/components/index.ts
- packages/remax/src/hostConfig.ts
resolve #33 
组件 `forwardRef`，并加上遗漏的 `getPublicInstance`
> fix: add missing getPublicInstance

- packages/remax-cli/src/getEntries.ts
> support subPackages entry

- packages/remax-cli/src/build/index.ts
> build: 让 bundle 信息好看一些

- packages/remax-cli/package.json
- packages/remax-cli/src/build/rollupConfig.ts
- packages/remax-cli/yarn.lock
> build: 支持 async await

- packages/remax/src/hostConfig.ts
> fix(remax): 虚拟dom修改也要触发 update

- packages/remax-cli/src/build/plugins/template.ts
- packages/remax-cli/templates/wechat/base.ejs
- packages/remax-cli/templates/wechat/component.ejs
> build: uglify 模板

- packages/remax-cli/package.json
- packages/remax-cli/src/build/rollupConfig.ts
- packages/remax-cli/yarn.lock
> build: 支持 sass, stylus

- packages/remax-cli/src/build/index.ts
> fix: bundle 启动时显示错误信息

- packages/remax-cli/package.json
- packages/remax-cli/src/build/plugins/template.ts
- packages/remax-cli/src/winPath.ts
- packages/remax-cli/typings/index.d.ts
- packages/remax-cli/yarn.lock
> fix: windows path

- packages/remax-cli/src/build/rollupConfig.ts
> fix: stylus typo

- packages/remax-cli/package.json
- packages/remax-cli/src/build/rollupConfig.ts
- packages/remax-cli/typings/index.d.ts
> build: build前清理输出目录，并保留.tea不删除

- packages/remax/src/adapters/wechat/components/Swiper.tsx
- packages/remax/src/adapters/wechat/components/index.ts
> fix: 微信Swiper自动播放不会受state变化影响

- packages/remax/src/adapters/alipay/components/Button.ts
- packages/remax/src/adapters/alipay/components/Canvas.ts
- packages/remax/src/adapters/alipay/components/Checkbox.ts
- packages/remax/src/adapters/alipay/components/CheckboxGroup.ts
- packages/remax/src/adapters/alipay/components/CoverImage.ts
- packages/remax/src/adapters/alipay/components/CoverView.ts
- packages/remax/src/adapters/alipay/components/Form.ts
- packages/remax/src/adapters/alipay/components/Icon.ts
- packages/remax/src/adapters/alipay/components/Image.ts
- packages/remax/src/adapters/alipay/components/Input.ts
- packages/remax/src/adapters/alipay/components/Label.ts
- packages/remax/src/adapters/alipay/components/Map.ts
- packages/remax/src/adapters/alipay/components/MovableArea.ts
- packages/remax/src/adapters/alipay/components/MovableView.ts
- packages/remax/src/adapters/alipay/components/Navigator.ts
- packages/remax/src/adapters/alipay/components/Picker.ts
- packages/remax/src/adapters/alipay/components/PickerView.ts
- packages/remax/src/adapters/alipay/components/PickerViewColumn.ts
- packages/remax/src/adapters/alipay/components/Progress.ts
- packages/remax/src/adapters/alipay/components/Radio.ts
- packages/remax/src/adapters/alipay/components/RadioGroup.ts
- packages/remax/src/adapters/alipay/components/RichText.ts
- packages/remax/src/adapters/alipay/components/ScrollView.ts
- packages/remax/src/adapters/alipay/components/Slider.ts
- packages/remax/src/adapters/alipay/components/Swiper.ts
- packages/remax/src/adapters/alipay/components/SwiperItem.ts
- packages/remax/src/adapters/alipay/components/Switch.ts
- packages/remax/src/adapters/alipay/components/Text.ts
- packages/remax/src/adapters/alipay/components/TextArea.ts
> add component types

- packages/remax-cli/src/build/plugins/page.ts
> fix: 修复页面组件不能命名为 Page 的问题

- packages/remax-cli/src/build/adapters/alipay/index.ts
- packages/remax-cli/src/build/adapters/index.ts
- packages/remax-cli/src/build/adapters/wechat/index.ts
- packages/remax-cli/src/build/rollupConfig.ts
- packages/remax-cli/src/getEntries.ts
> fix: 修复 tabBar 配置 iconPath 无效的问题

- packages/remax-cli/package.json
- packages/remax-cli/src/build/plugins/postcssUrl.ts
- packages/remax-cli/src/build/rollupConfig.ts
- packages/remax-cli/typings/index.d.ts
> fix: 修复支付宝 css 无法引用本地图片的问题

- packages/remax-cli/src/build/plugins/components.ts
> fix: 修复支付宝组件无法接受动态传递props的问题

- docs/guide/config.md
- packages/remax-cli/src/build/rollupConfig.ts
#201 
这样修改可以支持这几种方式
```
{
alias: {
'@components': './src/components',
'antd': './node_modules/antd-mobile/index.js',
'antd: require.resove('antd-mobile'),
'@utils': path.join(__dirname, 'src',  'utils')
}
}
```
> 修改config.alias 配置方式

- packages/remax-cli/src/build/plugins/template.ts
> fix: 在模板生成还未完成时就进行了生成资源操作

- packages/remax/src/adapters/wechat/api.ts
> fix(wechat): 添加微信遗漏的云开发 API

- packages/remax/src/__tests__/alipay/__snapshots__/index.test.tsx.snap
- packages/remax/src/__tests__/alipay/index.test.tsx
- packages/remax/src/utils/plainStyle.ts
> fix: 修复内联样式 vendor prefix 解析错误的问题

- packages/remax/src/__tests__/wechat/components/__snapshots__/Slider.test.tsx.snap
- packages/remax/src/adapters/wechat/components/Slider.ts
> fix(wechat): 修复 Slider 组件默认值错误的问题

- packages/remax-cli/src/__tests__/fixtures/cssUrl/expected/app.acss
- packages/remax-cli/src/__tests__/fixtures/cssUrl/src/pages/index.css
- packages/remax-cli/src/build/plugins/postcssUrl.ts
> fix: 修复 css 中 base64 的路径会被修改的问题

- packages/remax/src/__tests__/wechat/components/__snapshots__/Navigator.test.tsx.snap
- packages/remax/src/adapters/wechat/components/Navigator.ts
https://github.com/remaxjs/remax/issues/243#issuecomment-547771520
> fix(wechat): 设置 Navigator 组件 openType 默认值为 navigate

- packages/remax-cli/src/__tests__/helpers/build.ts
- packages/remax-cli/src/build/rollupConfig.ts
> perf(cli): 关闭 tree shaking 提升开发环境编译速度

- packages/remax/src/__tests__/alipay/__snapshots__/index.test.tsx.snap
- packages/remax/src/utils/plainStyle.ts
> fix: 修复 inline style 单位 px 没有转换成 rpx 的问题

- packages/remax-cli/package.json
- packages/remax-cli/src/checkVersions.ts
- packages/remax-cli/src/index.ts
> fix: add remax version check in project

- packages/remax-cli/src/__tests__/fixtures/universe/expected/wechat/base.wxml
- packages/remax-cli/src/__tests__/fixtures/wechat/expected/base.wxml
- packages/remax-cli/templates/wechat/base.ejs
- packages/remax-cli/templates/wechat/component.ejs
> fix(wechat): 修正 wx:key 的警告

- packages/remax-cli/package.json
> fix: 修复 node 10.10 打包出现 mkdir 的错误

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
> docs: add contributing guide

- packages/remax/src/adapters/alipay/components/Button.ts
> fix: update alipay button definition

- packages/remax/src/adapters/alipay/components/ContactButton.ts
- packages/remax/src/adapters/wechat/components/ScrollView.ts
add missing props type for Wechat's ScrollView
> rename LifestyleProps to ContactButtonProps of ContactButton.ts

- packages/remax-cli/src/build/rollupConfig.ts
修复 production 构建时会忽略 output 选项直接清空 dist/ 的问题
> fix: 修正 production 构建时的清理步骤

- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/src/index.axml
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/src/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/src/index.json
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/index.axml
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/index.json
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/src/components/src/index.axml
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/src/components/src/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/src/components/src/index.json
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/src/pages/index.js
- packages/remax-cli/src/build/plugins/nativeComponents/index.ts
> fix: 带有 src 目录的 npm 包小程序组件构建错误的问题

- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/index.js
- packages/remax-cli/src/build/plugins/nativeComponents/index.ts
把组件定义写在最下面，如果上面引用了这些变量，会出现变量未定义的情况。
> build: 调整小程序组件定义的位置

- packages/remax-cli/src/build/adapters/wechat/hostComponents/button.ts
> fix(wechat): 修复 spread 方式传递 Button 组件参数时 size 无效的问题

- docs/guide.md
- docs/guide/custom-component.md
- docs/guide/event.md
- packages/remax-cli/src/__tests__/fixtures/alipay/expected/pages/index.axml
- packages/remax-cli/src/__tests__/fixtures/assets/expected/pages/index.axml
- packages/remax-cli/src/__tests__/fixtures/babelrc/expected/pages/index.axml
- packages/remax-cli/src/__tests__/fixtures/customRootDir/expected/pages/index.axml
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/index.axml
- packages/remax-cli/src/__tests__/fixtures/toutiao/expected/base.ttml
- packages/remax-cli/src/__tests__/fixtures/universe/expected/alipay/pages/index.axml
- packages/remax-cli/src/__tests__/fixtures/universe/expected/toutiao/base.ttml
- packages/remax-cli/src/__tests__/fixtures/universe/expected/wechat/base.wxml
- packages/remax-cli/src/__tests__/fixtures/wechat/expected/base.wxml
- packages/remax-cli/src/build/plugins/components.ts
- packages/remax/src/Container.ts
- packages/remax/src/SyntheticEvent/Pool.ts
- packages/remax/src/SyntheticEvent/index.ts
- packages/remax/src/__tests__/SyntheticEvent.test.ts
- packages/remax/src/__tests__/alipay/__snapshots__/index.test.tsx.snap
- packages/remax/src/__tests__/alipay/index.test.tsx
- packages/remax/src/__tests__/wechat/__snapshots__/index.test.tsx.snap
- packages/remax/src/__tests__/wechat/index.test.tsx
- packages/remax/src/hostConfig.ts
resolve #283
废弃 catchtap 用法，resolve #279
> feat: stop propagation

- packages/remax-cli/src/build/plugins/nativeComponents/index.ts
> fix: 修复 extname 导致收集不到 page 的问题

- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/Hello.js
- packages/remax-cli/src/build/plugins/nativeComponents/babelPlugin.ts
> fix: 修改引用多个相同小程序组件时生成的 id 不一致的情况

- docs/guide/config.md
> docs(remax): 补全引号

- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/g/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/h/Hello.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/h/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/Hello.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/index.axml
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/index2.axml
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/index3.axml
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/index3.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/src/pages/index.js
- packages/remax-cli/src/build/plugins/nativeComponents/babelPlugin.ts
- packages/remax-cli/src/build/plugins/nativeComponents/index.ts
- packages/remax-cli/templates/alipay/component.ejs
- packages/remax/package.json
- packages/remax/src/__tests__/__snapshots__/createNativeComponent.test.tsx.snap
- packages/remax/src/__tests__/createNativeComponent.test.tsx
- packages/remax/src/createNativeComponent.ts
- packages/remax/src/index.ts
- packages/remax/tsconfig.json
```javascript
import React from 'react';
import { View } from 'remax/alipay';
import Badge from 'mini-antui/es/badge';
export default () => {
const badge = React.useRef();
return (
<View>
<Badge ref={badge}>
<View slot="inner">Remax</View>
</Badge>
</View>
);
}
```
> feat(alipay): 支持获取小程序组件 ref

- docs/guide/component.md
- package.json
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/expected/alipay/pages/index.axml
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/expected/alipay/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/expected/toutiao/base.ttml
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/expected/toutiao/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/expected/wechat/base.wxml
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/expected/wechat/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/src/pages/index.js
- packages/remax-cli/src/build/adapters/alipay/index.ts
- packages/remax-cli/src/build/adapters/index.ts
- packages/remax-cli/src/build/adapters/toutiao/index.ts
- packages/remax-cli/src/build/adapters/wechat/index.ts
- packages/remax-cli/src/build/plugins/components.ts
- packages/remax.macro/src/createHostComponent.ts
- packages/remax.macro/src/macro.ts
- packages/remax.macro/tests/fixtures/createHostComponent/imported/code.js
- packages/remax.macro/tests/fixtures/createHostComponent/multiple/code.js
- packages/remax.macro/tests/fixtures/createHostComponent/namedImported/code.js
- packages/remax.macro/tests/fixtures/createHostComponent/simple/code.js
- packages/remax/src/__tests__/__snapshots__/propsAlias.test.ts.snap
- packages/remax/src/__tests__/propsAlias.test.ts
- packages/remax/src/propsAlias.ts
- packages/remax/tsconfig.json
> feat: createHostComponent 支持定义 prop 别名

- .gitignore
- packages/babel-preset-remax/package.json
- packages/babel-preset-remax/src/index.ts
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/expected/alipay/pages/index.axml
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/expected/alipay/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/expected/toutiao/base.ttml
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/expected/toutiao/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/expected/wechat/base.wxml
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/expected/wechat/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/node_modules/custom-component/index.js
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/node_modules/custom-component/package.json
- packages/remax-cli/src/__tests__/fixtures/createHostComponent/src/pages/index.js
> fix: 修复安装的 lib 中 createHostComponent 不生效的问题

- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/app.json
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/index4.axml
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/index4.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/index4.json
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/src/app.config.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/src/pages/index4.tsx
- packages/remax-cli/src/build/plugins/nativeComponents/index.ts
> fix: 修复由于编译优化导致引入同一个原生组件的渲染错误

- packages/remax-cli/src/__tests__/fixtures/assets/expected/app.acss
- packages/remax-cli/src/__tests__/fixtures/assets/src/pages/index.css
- packages/remax-cli/src/build/plugins/postcssUrl.ts
> fix(cli): 修复多个 CSS 文件引用同一图片时报错的问题

- packages/babel-preset-remax/README.md
- packages/babel-preset-remax/src/index.ts
- packages/remax-cli/src/__tests__/customRootDir.test.ts
- packages/remax-cli/src/__tests__/fixtures/alipay/babel.config.js
- packages/remax-cli/src/__tests__/fixtures/babelrc/babel.config.js
- packages/remax-cli/src/__tests__/fixtures/babelrc/expected/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/babelrc/src/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/babelrc/src/pages/index.tsx
- packages/remax-cli/src/__tests__/fixtures/toutiao/babel.config.js
- packages/remax-cli/src/__tests__/fixtures/wechat/babel.config.js
- packages/remax-cli/src/build/plugins/babel.ts
- packages/remax-cli/src/build/rollupConfig.ts
> feat: babel-preset-remax 支持配置 typescript preset 参数

- docs/advanced-guide/sharing-state.md
- packages/remax-cli/src/__tests__/fixtures/reactDomAlias/expected/app.js
- packages/remax-cli/src/__tests__/fixtures/reactDomAlias/expected/app.json
- packages/remax-cli/src/__tests__/fixtures/reactDomAlias/expected/helper.sjs
- packages/remax-cli/src/__tests__/fixtures/reactDomAlias/expected/pages/index.axml
- packages/remax-cli/src/__tests__/fixtures/reactDomAlias/expected/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/reactDomAlias/expected/pages/index.json
- packages/remax-cli/src/__tests__/fixtures/reactDomAlias/node_modules/remax/esm/index.js
- packages/remax-cli/src/__tests__/fixtures/reactDomAlias/node_modules/remax/package.json
- packages/remax-cli/src/__tests__/fixtures/reactDomAlias/src/app.config.js
- packages/remax-cli/src/__tests__/fixtures/reactDomAlias/src/app.js
- packages/remax-cli/src/__tests__/fixtures/reactDomAlias/src/pages/index.js
- packages/remax-cli/src/__tests__/reactDomAlias.test.ts
- packages/remax-cli/src/build/plugins/alias.ts
通过将 react-dom alias 成 remax 以支持这些库
resolve #405
> feat: 支持直接使用 react-redux/mobx-react，废弃 remax-redux/mobx-remax

- packages/remax/src/VNode.ts
- packages/remax/src/__tests__/alipay/__snapshots__/index.test.tsx.snap
- packages/remax/src/__tests__/alipay/index.test.tsx
- packages/remax/src/__tests__/toutiao/__snapshots__/index.test.tsx.snap
- packages/remax/src/__tests__/toutiao/index.test.tsx
- packages/remax/src/__tests__/wechat/__snapshots__/index.test.tsx.snap
- packages/remax/src/__tests__/wechat/index.test.tsx
> fix: 修复改变元素顺序后，出现元素错乱的问题

- bin/prerelease
- package.json
- packages/babel-preset-remax/package.json
- packages/remax-cli/package.json
- packages/remax.macro/package.json
- packages/remax/package.json
- packages/umi-plugin-remax/package.json
* 增加环境变量和npm login 校验
~~先 build 再 test，满足 remax.macro 的测试逻辑~~
* build 命令简化，因为 prebuild 已经 build remax.macro 和 remax 了
> chore: tweak release flow

- packages/remax-cli/bin/remax
- packages/remax-cli/package.json
- packages/remax-cli/src/RemaxOptionsSchema.json
- packages/remax-cli/src/__tests__/config.test.ts
- packages/remax-cli/src/__tests__/fixtures/exception/remax.config/remax.config.js
- packages/remax-cli/src/build/index.ts
- packages/remax-cli/src/getConfig.ts
- packages/remax-cli/src/index.ts
- packages/remax-cli/src/readManifest.ts
- packages/remax-cli/tsconfig.json
> build: 支持 remax.config.js schema 校验

- package.json
- packages/babel-preset-remax/package.json
- packages/babel-preset-remax/src/index.ts
- packages/remax-cli/package.json
- packages/remax-cli/src/__tests__/fixtures/alipay/expected/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/alipay/src/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/typescript/expected/alipay/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/typescript/expected/toutiao/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/typescript/expected/wechat/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/typescript/src/pages/index.tsx
- packages/remax.macro/package.json
- packages/remax/package.json
- packages/remax/src/propsAlias.ts
- packages/umi-plugin-remax/package.json
- yarn.lock
> feat: 支持 typescript 3.7

- packages/babel-preset-remax/package.json
- packages/babel-preset-remax/src/index.ts
- packages/remax.macro/jest.config.js
- packages/remax.macro/package.json
- packages/remax.macro/src/macro.ts
- packages/remax.macro/tests/index.test.ts
- packages/remax.macro/typings/index.d.ts
> refactor: bring babel-plugin-macros back

- packages/remax-cli/src/build/plugins/nativeComponents/index.ts
> build: 优化支付宝开发编译速度

- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/_foo/a/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/a/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/b/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/c/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/complex/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/d/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/e/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/f/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/notInJSX/index.axml
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/notInJSX/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/notInJSX/index.json
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/slot/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/components/src/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/src/components/notInJSX/index.axml
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/src/components/notInJSX/index.js
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/src/components/notInJSX/index.json
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/src/pages/index.js
- packages/remax-cli/src/build/plugins/nativeComponents/index.ts
- packages/remax-cli/src/build/plugins/nativeComponents/jsHelper.ts
> fix: 修复未使用JSX方式调用自定义组件报错的问题

- packages/remax-cli/src/__tests__/fixtures/alipay/expected/app.json
- packages/remax-cli/src/__tests__/fixtures/alipay/src/app.config.js
- packages/remax-cli/src/getEntries.ts
> fix: 当配置的页面不存在时有提醒信息

- packages/umi-plugin-remax/README.md
> docs: fix plugin usage typo

- packages/remax/src/__tests__/__snapshots__/propsAlias.test.ts.snap
- packages/remax/src/__tests__/propsAlias.test.ts
- packages/remax/src/utils/plainStyle.ts
> fix: 修复无法在 inline style 中使用 css3 var 特性的问题

- packages/remax-cli/src/__tests__/fixtures/wechat/expected/base.wxml
- packages/remax-cli/src/__tests__/fixtures/wechat/expected/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/wechat/src/pages/index.js
- packages/remax-cli/src/build/plugins/components.ts
- packages/remax/src/__tests__/wechat/components/ScrollView.test.tsx
- packages/remax/src/__tests__/wechat/components/__snapshots__/ScrollView.test.tsx.snap
- packages/remax/src/adapters/wechat/components/ScrollView.tsx
> fix(wechat): 修复微信平台 ScrollView 设置 scrollTop 表现异常的问题

- packages/remax/src/adapters/alipay/api.ts
> fix(alipay): 支付宝添加 getOpenUserInfo API

- packages/remax-cli/src/__tests__/fixtures/babelrc/expected/pages/index.js
- packages/remax/src/__tests__/alipay/index.test.tsx
- packages/remax/src/__tests__/hostConfig/diffProperties.test.ts
- packages/remax/src/hostConfig/diffProperties.ts
- packages/remax/src/hostConfig/index.ts
> perf: 避免当组件上有 style 属性时可能产生的非必要渲染

- docs/guide/framework.md
- packages/remax/src/Container.ts
- packages/remax/src/__tests__/alipay/index.test.tsx
- packages/remax/src/hooks.ts
- packages/remax/src/nativeEffect.ts
> feat: 引入 unstable_useNativeEffect

- packages/remax/alipay.d.ts
- packages/remax/package.json
- packages/remax/wechat.d.ts
> fix: 修复 api 类型丢失的问题

- packages/babel-preset-remax/README.md
- packages/babel-preset-remax/src/index.ts
- packages/remax-cli/src/__tests__/fixtures/namespaceAttribute/babel.config.js
- packages/remax-cli/src/__tests__/fixtures/namespaceAttribute/expected/app.acss
- packages/remax-cli/src/__tests__/fixtures/namespaceAttribute/expected/app.js
- packages/remax-cli/src/__tests__/fixtures/namespaceAttribute/expected/app.json
- packages/remax-cli/src/__tests__/fixtures/namespaceAttribute/expected/pages/index.axml
- packages/remax-cli/src/__tests__/fixtures/namespaceAttribute/expected/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/namespaceAttribute/expected/pages/index.json
- packages/remax-cli/src/__tests__/fixtures/namespaceAttribute/src/app.config.js
- packages/remax-cli/src/__tests__/fixtures/namespaceAttribute/src/app.js
- packages/remax-cli/src/__tests__/fixtures/namespaceAttribute/src/pages/index.css
- packages/remax-cli/src/__tests__/fixtures/namespaceAttribute/src/pages/index.js
- packages/remax-cli/src/__tests__/namespaceAttribute.test.ts
- packages/remax-cli/src/build/plugins/components.ts
> feat: 支持使用命名空间属性

- docs/guide/framework.md
- packages/remax/src/AppInstanceContext.ts
- packages/remax/src/__tests__/AppInstanceContext.test.ts
- packages/remax/src/__tests__/app.test.tsx
- packages/remax/src/createAppConfig.ts
- packages/remax/src/hooks.ts
- packages/remax/src/lifecycle.ts
> feat(remax): 为 App 添加 hooks

- packages/remax/src/__tests__/__snapshots__/index.test.tsx.snap
- packages/remax/src/__tests__/index.test.tsx
- packages/remax/src/utils/plainStyle/CSSProperty.ts
- packages/remax/src/utils/plainStyle/index.ts
> feat(remax): 支持 inline style 属性值不写单位，默认为 rpx

- packages/remax-cli/src/__tests__/fixtures/alipay/expected/app.js
- packages/remax-cli/src/__tests__/fixtures/alipay/expected/assets/images/cat.png.js
- packages/remax-cli/src/__tests__/fixtures/alipay/src/app.js
- packages/remax-cli/src/build/rollupConfig.ts
> fix: 修复当 app 文件引入图片，导致样式文件丢失的问题

- packages/remax-toutiao/src/hostComponents/Video/index.ts
修改 `VideoProps`， 对齐头条小程序 Video 组件
[头条小程序 Video 组件文档](https://microapp.bytedance.com/dev/cn/mini-app/develop/component/media-component/video)
> refactor: 优化头条 Video 组件属性 VideoProps

- packages/remax-cli/src/__tests__/fixtures/createHostComponent/expected/toutiao/index.js
- packages/remax-cli/src/__tests__/fixtures/toutiao/expected/base.ttml
- packages/remax-cli/src/__tests__/fixtures/toutiao/expected/index.js
- packages/remax-cli/src/__tests__/fixtures/typescript/expected/toutiao/index.js
- packages/remax-cli/src/__tests__/fixtures/universe/expected/toutiao/index.js
- packages/remax-toutiao/src/hostComponents/View/node.ts
> feat(remax): 头条 View 组件增加 onClick

- packages/remax-cli/src/build/plugins/rename.ts
> fix: 修复使用 typescript 时 common chunk 可能存在错误引用的问题

- packages/remax-cli/src/__tests__/fixtures/toutiao/expected/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/typescript/expected/toutiao/Text-chunk.js
- packages/remax-cli/src/__tests__/fixtures/universe/expected/toutiao/pages/index.js
- packages/remax-toutiao/src/api/index.ts
1. [canIUse](https://developer.toutiao.com/dev/cn/mini-app/develop/api/foundation/tt.caniuse)
2. [navigatetovideoview](https://developer.toutiao.com/dev/cn/mini-app/develop/api/retweet/tt.navigatetovideoview)
> feat(remax): 支持字节小程序新增api canIUse、navigateToVideoView

- packages/remax-cli/src/build/styleConfig.ts
> fix: 修复使用 scss 出错的问题

- packages/remax/src/createPageConfig.web.tsx
> fix(web): 修复 web 端 title 配置不生效的问题

- packages/remax-cli/src/build/webpack/loaders/manifest.ts
- packages/remax-cli/src/build/webpack/plugins/WebEntryWatcher.ts
- packages/remax-cli/src/build/webpack/plugins/index.ts
- packages/remax-cli/src/web/webpackConfig.web.ts
> fix(cli): 修复 app.config.ts 和 [page].config.ts 没有触发重新编译的问题

- packages/remax-cli/bin/remax
- packages/remax-cli/package.json
- packages/remax-cli/src/__tests__/fixtures/one/expected/ali/packageA/pages/index~pages/index.js
- packages/remax-cli/src/__tests__/fixtures/one/expected/toutiao/packageA/pages/index~pages/index.js
- packages/remax-cli/src/__tests__/fixtures/one/expected/web/index.css
- packages/remax-cli/src/__tests__/fixtures/one/expected/web/index.html
- packages/remax-cli/src/__tests__/fixtures/one/expected/web/index.js
- packages/remax-cli/src/__tests__/fixtures/one/expected/web/packageA/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/one/expected/web/packageA/pages/index~pages/index.css
- packages/remax-cli/src/__tests__/fixtures/one/expected/web/packageA/pages/index~pages/index.js
- packages/remax-cli/src/__tests__/fixtures/one/expected/web/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/one/expected/web/runtime-test.js
- packages/remax-cli/src/__tests__/fixtures/one/expected/web/vendors~packageA/pages/index~pages/index.js
- packages/remax-cli/src/__tests__/fixtures/one/expected/wechat/packageA/pages/index~pages/index.js
- packages/remax-cli/src/build/webpack/config.web.ts
- packages/remax-cli/template/entry.js.ejs
- packages/remax-one/src/__tests__/components/Textarea.test.tsx
- packages/remax-one/src/__tests__/components/__snapshots__/Textarea.test.tsx.snap
- packages/remax-one/src/hostComponents/Button/index.web.tsx
- packages/remax-one/src/hostComponents/Image/index.css
- packages/remax-one/src/hostComponents/Image/index.web.tsx
- packages/remax-one/src/hostComponents/Input/index.web.tsx
- packages/remax-one/src/hostComponents/Text/index.css
- packages/remax-one/src/hostComponents/Text/index.web.tsx
- packages/remax-one/src/hostComponents/Textarea/index.ts
- packages/remax-one/src/hostComponents/Textarea/index.web.tsx
- packages/remax-one/src/hostComponents/WebView/index.web.tsx
- packages/remax/bin/remax
- packages/remax/package.json
- packages/remax/web/app.css
1. 调整 web 组件样式
2. 修复 web 下 App 不是第一个 entry 的问题
3. 修复 remax 命令可能出错的问题
> refactor: 调整 web 组件样式

- packages/remax-cli/package.json
- packages/remax-cli/src/build/webpack/config.mini.ts
- packages/remax-cli/src/build/webpack/config.web.ts
- packages/remax-cli/typings/index.d.ts
- yarn.lock
> refactor: use webpackbar instead of progress-bar

- packages/remax-cli/src/__tests__/fixtures/ali/expected/app.json
- packages/remax-cli/src/__tests__/fixtures/ali/expected/packageA/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/ali/expected/pages/classPage.axml
- packages/remax-cli/src/__tests__/fixtures/ali/expected/pages/classPage.js
- packages/remax-cli/src/__tests__/fixtures/ali/expected/pages/classPage.json
- packages/remax-cli/src/__tests__/fixtures/ali/src/app.config.js
- packages/remax-cli/src/__tests__/fixtures/ali/src/app.js
- packages/remax-cli/src/__tests__/fixtures/ali/src/pages/classPage.js
- packages/remax-cli/src/build/babel/appEvent.ts
- packages/remax-cli/src/build/babel/pageEvent.ts
- packages/remax-cli/src/build/webpack/config.mini.ts
> 2.0 修复 class 组件生命周期有可能不生效的问题

- packages/remax-cli/src/__tests__/fixtures/reactDomAlias/expected/pages/index.js
- packages/remax-cli/src/build/babel/appEvent.ts
- packages/remax-runtime/src/createAppConfig.ts
> fix: 修复部分 App 生命周期不生效的问题

- docs/guide/advanced/typescript.md
- docs/guide/one/index.md
- docs/guide/quick-start.md
> chore: update doc with create-remax-app

- packages/remax-cli/src/build/utils/modules.ts
> fix(cli): 修复生产环境生命周期和自定义组件可能无效的问题

- docs/guide/basic/custom-component.md
发现注意事项这里的错误和正确的例子是一样的，参照`v1`的例子修改了下
> docs:  更新custom-component.md注意事项部分的例子

- packages/remax-toutiao/src/__tests__/components/__snapshots__/Input.test.tsx.snap
- packages/remax-toutiao/src/hostComponents/Input/index.ts
> fix(toutiao): add Input default props

- packages/remax-toutiao/src/__tests__/components/Canvas.test.tsx
- packages/remax-toutiao/src/__tests__/components/__snapshots__/Canvas.test.tsx.snap
- packages/remax-toutiao/src/hostComponents/Canvas/index.ts
> fix(toutiao): fix canvasId typo

- packages/remax-cli/src/__tests__/integration/fixtures/lifeCycle/expected/remax-vendors.js
- packages/remax-cli/src/__tests__/integration/fixtures/runtime-plugin/expected/remax-vendors.js
- packages/remax-runtime/src/__tests__/index.test.tsx
- packages/remax-runtime/src/hostConfig/index.ts
- 有单元测试
- 已在微信和支付宝小程序下测试过
Fixes #985
> feat(remax): 小程序端支持suspense data fetching

- .github/workflows/test.yml
> ci: run actions on pull_request

- packages/remax-cli/src/__tests__/integration/fixtures/lifeCycle/expected/remax-vendors.js
- packages/remax-cli/src/__tests__/integration/fixtures/runtime-plugin/expected/remax-vendors.js
- packages/remax-runtime/src/__tests__/createPageConfig.test.tsx
- packages/remax-runtime/src/__tests__/page.test.tsx
- packages/remax-runtime/src/createAppConfig.ts
- packages/remax-runtime/src/createPageConfig.ts
- packages/remax-runtime/src/lifecycle/index.ts
除了 onShareAppMessage 和 onPageScroll，其他生命周期都可以默认注册
> refactor(remax): 默认注册大部分生命周期

- .gitattributes
> chore: add .gitattribtues

- packages/remax-cli/src/__tests__/integration/fixtures/lifeCycle/expected/remax-vendors.js
- packages/remax-cli/src/__tests__/integration/fixtures/runtime-plugin/expected/remax-vendors.js
- packages/remax-runtime/src/__tests__/__snapshots__/propsAlias.test.ts.snap
- packages/remax-runtime/src/__tests__/propsAlias.test.ts
- packages/remax-runtime/src/propsAlias.ts
> fix(remax): 修复 style 属性解析报错

- docs/guide/framework/event.md
- packages/remax-cli/src/__tests__/integration/fixtures/lifeCycle/expected/remax-vendors.js
- packages/remax-cli/src/__tests__/integration/fixtures/runtime-plugin/expected/remax-vendors.js
- packages/remax-runtime/src/SyntheticEvent/constants.ts
> feat(remax): onTouchStart onTouchMove onTouchEnd 支持阻止冒泡

- packages/remax-cli/src/OptionsSchema.json
- packages/remax-cli/src/__tests__/integration/__snapshots__/config.test.ts.snap
- packages/remax-cli/src/__tests__/integration/fixtures/exception/remax.config/remax.config.js
- packages/remax-cli/src/build/mini.ts
- packages/remax-cli/src/build/utils/output.ts
> fix(cli): 修复 notify 命令不生效的问题

- packages/remax-cli/src/__tests__/integration/fixtures/lifeCycle/expected/remax-vendors.js
- packages/remax-cli/src/__tests__/integration/fixtures/runtime-plugin/expected/remax-vendors.js
- packages/remax-runtime/src/Container.ts
- packages/remax-runtime/src/__tests__/index.test.tsx
> fix(wechat): 修复更新已删除的节点导致报错的问题

- packages/remax-cli/src/__tests__/integration/fixtures/lifeCycle/expected/remax-vendors.js
- packages/remax-cli/src/__tests__/integration/fixtures/runtime-plugin/expected/remax-vendors.js
- packages/remax-runtime/src/Container.ts
- packages/remax-runtime/src/VNode.ts
- packages/remax-runtime/src/__tests__/__snapshots__/index.test.tsx.snap
- packages/remax-runtime/src/__tests__/index.test.tsx
- packages/remax-runtime/src/__tests__/index.wechat.test.tsx
> fix(wechat): 修复条件渲染错误

- packages/remax-one/src/__tests__/createEvent.test.ts
- packages/remax-one/src/createHostComponent.ts
- packages/remax-one/src/types/event.ts
> fix(one): 修复 TouchEvent stopPropagation 属性

- e2e/dummy/src/pages/two/index.js
- e2e/dummy/tests/index.test.js
- packages/remax-cli/src/__tests__/integration/fixtures/lifeCycle/expected/app.js
- packages/remax-cli/src/__tests__/integration/fixtures/lifeCycle/expected/pages/classPage.js
- packages/remax-cli/src/__tests__/integration/fixtures/lifeCycle/expected/pages/index.js
- packages/remax-cli/src/__tests__/integration/fixtures/lifeCycle/expected/remax-vendors.js
- packages/remax-cli/src/__tests__/integration/fixtures/runtime-plugin/expected/app.js
- packages/remax-cli/src/__tests__/integration/fixtures/runtime-plugin/expected/pages/index.js
- packages/remax-cli/src/__tests__/integration/fixtures/runtime-plugin/expected/remax-vendors.js
- packages/remax-runtime/src/createPageConfig.web.tsx
- packages/remax-runtime/src/hooks/index.ts
- packages/remax-runtime/src/hooks/useQuery.ts
- packages/remax-runtime/src/hooks/useQuery.web.ts
> fix(web): 修复 web 下 useQuery 无法获取到参数的问题

- packages/remax-cli/src/build/web.ts
- packages/remax-cli/src/build/webpack/config.mini.ts
- packages/remax-cli/src/build/webpack/config.web.ts
> fix: 修复 externals 配置可能被覆盖的问题

- packages/remax-runtime/src/AppContainer.ts
- packages/remax-runtime/src/Container.ts
- packages/remax-runtime/src/VNode.ts
- packages/remax-runtime/src/__tests__/__snapshots__/index.test.tsx.snap
- packages/remax-runtime/src/__tests__/createPageConfig.test.tsx
- packages/remax-runtime/src/__tests__/index.test.tsx
- packages/remax-runtime/src/__tests__/page.test.tsx
- packages/remax-runtime/src/createAppConfig.ts
- packages/remax-runtime/src/hostConfig/index.ts
> refactor: 去掉 Promise.resolve

- docs/guide/advanced/plugin.md
- packages/remax-cli/src/API.ts
- packages/remax-cli/src/build/index.ts
- packages/remax-runtime/src/PluginDriver.ts
- packages/remax-runtime/src/RuntimeOptions.ts
- packages/remax-runtime/src/__tests__/PluginDriver.test.ts
- packages/remax-runtime/src/__tests__/RuntimeOptions.test.ts
- packages/remax-runtime/src/__tests__/app.test.tsx
- packages/remax-runtime/src/__tests__/createPageConfig.test.tsx
- packages/remax-runtime/src/__tests__/createPageWrapper.test.tsx
- packages/remax-runtime/src/__tests__/index.test.tsx
- packages/remax-runtime/src/__tests__/page.test.tsx
- packages/remax-runtime/src/createAppConfig.ts
- packages/remax-runtime/src/createPageConfig.ts
- packages/remax-runtime/src/createPageConfig.web.tsx
- packages/remax-runtime/src/createPageWrapper.ts
- packages/remax-types/src/index.ts
- 新增运行时 `onAppComponent`
- 新增运行时 `onPageComponent`
- 调整运行时 `onPageConfig` 新增 page 参数
- 新增编译时 `onBuildStart`
> 新增一波插件 hooks

- CONTRIBUTING.md
> docs: update remax implementation-notes link

- packages/remax-runtime/src/index.ts
> fix: 修复使用 react-query@2.21.0 构建报错的问题

- packages/remax-runtime/src/hooks/useQuery.ts
- packages/remax-runtime/src/hooks/useQuery.web.ts
fix: useQuery return object's key maybe is undefined
> fix: useQuery return type

- packages/remax-runtime/src/VNode.ts
- packages/remax-runtime/src/__tests__/__snapshots__/index.toutiao.test.tsx.snap
- packages/remax-runtime/src/__tests__/__snapshots__/index.wechat.test.tsx.snap
- packages/remax-runtime/src/__tests__/helpers/setupGlobals.ts
- packages/remax-runtime/src/__tests__/index.wechat.test.tsx
> fix(wechat): 修复微信端节点交换时渲染错误的问题

- packages/remax-cli/src/__tests__/integration/fixtures/web/expected/index.js
- packages/remax-cli/src/__tests__/integration/fixtures/web/expected/runtime.js
- packages/remax-cli/src/build/entries/SpaEntry.ts
- packages/remax-cli/src/build/webpack/config.web.mpa.ts
- packages/remax-cli/src/build/webpack/config.web.ts
- packages/remax-web/src/__tests__/createApp.test.tsx
- packages/remax-web/src/createApp.tsx
- packages/remax-web/src/types/index.ts
> Remaxjs fix#1383

- packages/remax-runtime/src/__tests__/propsAlias.test.ts
- packages/remax-runtime/src/propsAlias.ts
> feat: 提升平台前缀属性权重

- packages/remax-wechat/src/hostComponents/Image/index.ts
> fix(wechat): Image 组件 mode 属性添加 heightFix

- packages/remax-cli/src/builtinPlugins.ts
- packages/remax-plugin-error-screen/src/ErrorBoundary.tsx
- packages/remax-runtime/package.json
- packages/remax-web/package.json
- yarn.lock
> chore: use the same version of react-is

- docs/guide/basic/cli.md
- packages/remax-cli/src/build/index.ts
- packages/remax-cli/src/build/utils/output.ts
- packages/remax-cli/src/build/webpack/config.mini.ts
- packages/remax-cli/src/build/webpack/config.miniPlugin.ts
- packages/remax-cli/src/index.ts
- packages/remax-types/src/index.ts
> chore: build & cli 增加 --loglevel 参数

- .github/.gitleaks.toml
- .github/workflows/gitleaks.yml
- create `.github/.gitleaks.toml` for the convenience of future revisions (based on [ycjcl868/gitleaks](https://github.com/ycjcl868/gitleaks))
- `fetch-depth: '1'` will cause the `object not found` error (as [mentioned](https://github.com/zricethezav/gitleaks-action#note) in gitleaks-action)
- `whitelist` to `allowlist`
- `fileNameRegex` to `file`
cc @afc163 
---
~*Update*~
~found [an issue](https://github.com/zricethezav/gitleaks-action/issues/17) on gitleaks-action~
*FIXED*
> ci: create .github/.gitleaks.toml

- docs/guide/basic/custom-component.md
分享直接使用微信小程序的自定义组件weui 组件的演示代码，避免其他人再去摸索
> docs: 添加 weui 组件的演示代码

- e2e/app/package.json
- e2e/app/tests/preset.js
- package.json
- packages/babel-plugin-remax-host-component/jest.config.js
- packages/babel-plugin-remax-lifecycle/jest.config.js
- packages/babel-plugin-remax-regenerator-runtime/jest.config.js
- packages/babel-plugin-remax-turbo-render/jest.config.js
- packages/babel-preset-remax/jest.config.js
- packages/remax-ali/jest.config.js
- packages/remax-cli/jest.config.js
- packages/remax-framework-shared/jest.config.js
- packages/remax-macro/jest.config.js
- packages/remax-one/jest.config.js
- packages/remax-runtime/jest.config.js
- packages/remax-shared/jest.config.js
- packages/remax-toutiao/jest.config.js
- packages/remax-wechat/jest.config.js
- yarn.lock
https://jestjs.io/blog/2021/05/25/jest-27
> chore: upgrade jest to 27

- packages/remax-cli/src/readManifest.ts
https://github.com/remaxjs/remax/issues/1535#issue-860276180
> fix: 修复watch模式下app.config配置更新问题

- packages/remax-runtime/package.json
- packages/remax-runtime/src/Container.ts
- packages/remax-runtime/src/__tests__/index.test.tsx
- packages/remax-runtime/src/__tests__/index.toutiao.test.tsx
- packages/remax-runtime/src/__tests__/index.wechat.test.tsx
- packages/remax-runtime/src/__tests__/page.test.tsx
- packages/remax-runtime/src/createPageConfig.ts
- packages/remax-runtime/src/hostConfig/index.ts
- packages/remax-runtime/src/render.ts
- yarn.lock
> feat: 生命周期 & 交互事件支持 batchedUpdates

- e2e/app/mini.project.json
- e2e/app/package.json
- e2e/app/src/pages/index/index.js
- packages/remax-one/src/hostComponents/Button/index.web.tsx
> feat: 调整remax/one的button组件dom结构

- packages/remax-runtime/src/createComponentConfig.wechat.ts
https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html
跟react组件保持一致，可以通过外部css来改变样式
> feat: 可以通过外部修改组件样式

- docs/index.md
> docs: 修复文档中web应用无法预览问题

- packages/remax-one/src/hostComponents/Button/index.web.tsx
- packages/remax-web/assets/app.css
> fix: 调整Button组件的dom标签

- docs/guide/one/web.md
- e2e/app/src/pages/index/index.js
- packages/remax-web/assets/app.css
close #1722 
- 修复文档错误，tabbar 参数‘activeTitleColor’应该为'selectedColor'（与小程序对齐）
- tabbar移除a:any-link下划线样式
> fix: #1722

- packages/remax-one/src/api/index.wechat.ts
> refactor(one): 不再从 @remax/wechat 引用 api

- packages/remax-toutiao/src/api/index.ts
> feat(toutiao): 新增ai/ar能力接口

- docs/guide/quick-start.md
> docs: 修改快速上手文档，加入ts模板创建命令

- packages/remax-wechat/src/hostComponents/Video/index.ts
> fix(wechat): #1510
