remaxjs/remax

- packages/@remax/core/src/index.js
现在每次 React 有 patch 变更时都会触发 setData，虽然推测小程序可能存在优化，但是仍然把一段时间内多次 setData merge 掉比较好（现在暂定 1000ms/60，类似于 requestAnimationFrame）
> merge setData every 1000/60ms(for 60fps)

- packages/remax/src/__tests__/index.test.tsx
- packages/remax/src/createPageConfig.ts
- packages/remax/src/hostConfig.ts
resolve #52
由此可见，可能我们需要区分 setState 操作和 hostConfig 中的 update 操作。
先处理 `appendChildToContainer`，后续再讨论
> fix(remax): 在第一次 render 阶段直接执行 update 操作

- packages/remax-cli/package.json
在 remax-cli 里引入了 acorn-walk 但是没在 package.json 里声明，导致在用  remax-cli 创建启动项目时报错找不到 acorn-walk 的依赖。
> fix: 增加 remax-cli 缺失的 acorn-walk 依赖

- packages/remax-cli/src/build/rollupConfig.ts
- packages/remax-cli/src/types.ts
使以`APP_`和`REMAX_`开头的名称的环境变量可通过`process.env`被访问。
使用场景参见：[https://create-react-app.dev/docs/adding-custom-environment-variables](https://create-react-app.dev/docs/adding-custom-environment-variables)
> 使编译时的特定环境变量可被访问并使其在解构赋值时工作

- packages/remax-cli/package.json
- packages/remax-cli/src/build/index.ts
- packages/remax-cli/src/build/utils/checkChokidar.ts
- packages/remax-cli/src/build/utils/output.ts
- packages/remax-cli/src/build/watcher.ts
- packages/remax-cli/src/getConfig.ts
不好意思，更新晚了，现在extraFiles数组可以添加文件的配置，这部分的watch是要重新build的，把需要的监听文件放进去就可以了
> fix: rollup watch

- packages/remax-cli/src/build/rollupConfig.ts
https://github.com/remaxjs/remax/issues/224
> fix: 图片资源编译以后目录和 src 下不一致

- packages/remax-cli/src/__tests__/index.test.ts
- packages/remax-cli/src/build/plugins/components.ts
- packages/remax-cli/src/build/plugins/template.ts
- packages/remax-cli/templates/alipay/base.ejs
- packages/remax-cli/templates/wechat/base.ejs
目前微信必须显式得在 jsx 中调用 remax 组件，才会收集到 remax 组件信息。现在修改成从 import 语句收集组件信息，就可以使微信支持更动态的写法
> fix: 修复较为动态地使用 Remax 组件时可能不会渲染的问题

- docs/guide/config.md
- packages/remax-cli/src/build/rollupConfig.ts
- packages/remax-cli/src/getConfig.ts
添加 postcss 配置项，用于添加 less/stylus/sass  的配置 等
```
{
postcss: {
use: [
['less', { 
paths: [path.resolve(__dirname, 'src/asset/style')] 
}]
]
}
}
```
> feat: 添加postcss 配置项

- packages/remax-cli/src/getConfig.ts
> fix: 修复 rebuild 读取到错误的 remax config 文件的问题

- packages/remax/src/createPageConfig.ts
修复阿里小程序 sePageScroll 的回调传参是undefined
> fix: page lifecye pageScroll callback‘s params is undefined issue

- packages/remax-cli/src/__tests__/fixtures/alipay/expected/helper.sjs
- packages/remax-cli/src/__tests__/fixtures/assets/expected/helper.sjs
- packages/remax-cli/src/__tests__/fixtures/babelrc/expected/helper.sjs
- packages/remax-cli/src/__tests__/fixtures/customRootDir/expected/helper.sjs
- packages/remax-cli/src/__tests__/fixtures/nativeComponent/expected/helper.sjs
- packages/remax-cli/src/__tests__/fixtures/universe/expected/alipay/helper.sjs
- packages/remax-cli/src/__tests__/fixtures/universe/expected/wechat/helper.wxs
- packages/remax-cli/src/__tests__/fixtures/wechat/expected/helper.wxs
- packages/remax-cli/templates/helper.js
- packages/remax/src/Container.ts
- packages/remax/src/__tests__/alipay/index.test.tsx
- packages/remax/src/actionId.ts
实际上是钉钉小程序本身的bug，我们通过废弃已处理过的action来避免这个问题
fix #316
> fix: 修复钉钉小程序使用原生组件渲染错乱的问题

- packages/remax/src/Container.ts
- packages/remax/src/VNode.ts
- packages/remax/src/__tests__/propsAlias.test.ts
- packages/remax/src/__tests__/wechat/__snapshots__/index.test.tsx.snap
- packages/remax/src/__tests__/wechat/index.test.tsx
- packages/remax/src/adapters/alipay/components/factory.ts
- packages/remax/src/adapters/toutiao/components/factory.ts
- packages/remax/src/adapters/wechat/components/Input.tsx
- packages/remax/src/adapters/wechat/components/Swiper.tsx
- packages/remax/src/adapters/wechat/components/Textarea.tsx
- packages/remax/src/adapters/wechat/components/Video.tsx
- packages/remax/src/adapters/wechat/components/factory.ts
- packages/remax/src/propsAlias.ts
> fix: 修复原生组件驼峰风格，React风格函数属性转换错误的问题

- packages/babel-preset-remax/README.md
- packages/babel-preset-remax/src/index.ts
- packages/remax-cli/src/__tests__/fixtures/babelrc/babel.config.js
- packages/remax-cli/src/__tests__/fixtures/babelrc/expected/components/a/index.axml
- packages/remax-cli/src/__tests__/fixtures/babelrc/expected/components/a/index.js
- packages/remax-cli/src/__tests__/fixtures/babelrc/expected/components/a/index.json
- packages/remax-cli/src/__tests__/fixtures/babelrc/expected/pages/index.axml
- packages/remax-cli/src/__tests__/fixtures/babelrc/expected/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/babelrc/expected/pages/index.json
- packages/remax-cli/src/__tests__/fixtures/babelrc/src/components/a/index.axml
- packages/remax-cli/src/__tests__/fixtures/babelrc/src/components/a/index.js
- packages/remax-cli/src/__tests__/fixtures/babelrc/src/components/a/index.json
- packages/remax-cli/src/__tests__/fixtures/babelrc/src/index.d.ts
- packages/remax-cli/src/__tests__/fixtures/babelrc/src/pages/index.tsx
- packages/remax-cli/src/build/plugins/babel.ts
```js
presets: [
[
'remax',
{
typescript: {
allowNamespaces: true,
},
'class-properties': {
loose: true,
},
decorators: {
legacy: true,
},
},
],
];
}
```
> feat: babel-preset-remax 增加 decorators 和 class-properties 配置项

- packages/remax/src/__tests__/__snapshots__/createNativeComponent.test.tsx.snap
- packages/remax/src/__tests__/createNativeComponent.test.tsx
- packages/remax/src/createNativeComponent.ts
> fix: 去除没有使用 ref 时原生自定义组件抛出无用的警告

- packages/remax/src/SyntheticEvent/Pool.ts
- packages/remax/src/SyntheticEvent/index.ts
- packages/remax/src/__tests__/SyntheticEvent.test.ts
修复 issue #552 
目前破坏了 `do not stop propagation when unexpected event happens` 测试用例。不太理解这个用例的目的是什么，看起来没什么意义，望告知。
> fix(remax): 修复 initialEventState 记录的初始 currentEventId 错误的问题

- packages/remax-toutiao/src/hostComponents/Button/index.ts
如题，简单修改onGetPhoneNumber事件名，会导致现有项目onGetphonenumber事件失效
> fix: 修正头条小程序button组件onGetPhoneNumber事件大小写拼写问题

- packages/remax-cli/src/__tests__/fixtures/env/expected/pages/index.js
- packages/remax-cli/src/__tests__/fixtures/env/src/pages/index.js
- packages/remax-cli/src/build/env.ts
直接替换 `process.env` 会匹配到 `g.process.env` 导致语法错误。
比如：node_modules/lib/mobx.module.js
> fix: 修复环境变量注入导致的语法错误

- packages/remax-cli/src/build/rollupConfig.ts
在 [postcss-modules](https://github.com/css-modules/postcss-modules) 中，可以看到 `modules` 是可以配置额外的参数的，例如
```js
{
modules: {
generateScopedName: "[name]__[local]___[hash:base64:5]"
}
}
```
而目前只配置了 `globalModulePaths` 参数，无法配置更多的 `postcss-modules` 参数选项
> feat(cli): 支持 css modules 更多配置

- packages/remax-alipay/src/node/index.ts
- packages/remax-cli/src/__tests__/fixtures/alipay/expected/app.json
- packages/remax-cli/src/__tests__/fixtures/alipay/src/app.config.js
- packages/remax-cli/src/__tests__/fixtures/toutiao/expected/app.json
- packages/remax-cli/src/__tests__/fixtures/toutiao/src/app.config.js
- packages/remax-cli/src/__tests__/fixtures/wechat/expected/app.json
- packages/remax-cli/src/__tests__/fixtures/wechat/src/app.config.js
- packages/remax-toutiao/src/node/index.ts
- packages/remax-wechat/src/node/index.ts
> fix: 修复 tabBar icon 使用网络图片编译报错的问题

- docs/faq.md
更新webstorm编辑器下使用Remax，webstorm无提示的设置方法，便于新人在入手Remax时候IDE没有提示的困惑。
> 更新webstorm下api类型无提示设置方法

- package.json
- packages/babel-preset-remax/package.json
- packages/postcss-remax-tag/package.json
- packages/remax-ali/package.json
- packages/remax-cli/package.json
- packages/remax-macro/package.json
- packages/remax-one/package.json
- packages/remax-router/package.json
- packages/remax-runtime/package.json
- packages/remax-toutiao/package.json
- packages/remax-types/package.json
- packages/remax-web/package.json
- packages/remax-wechat/package.json
- packages/remax/package.json
- website/package.json
- yarn.lock
为 workspace 下的所有 package 增加了 clean（rimraf）
方便执行 `yarn workspaces run clean` 来重置编译结果
> chore: use rimraf in scripts

- .travis.yml
travis 里配置了识别 docs 开头执行 deploy 任务，但是 [一直](https://travis-ci.org/github/remaxjs/remax/builds/686882267?utm_source=github_status&utm_medium=notification) [失败](https://travis-ci.org/github/remaxjs/remax/builds/686846733?utm_source=github_status&utm_medium=notification)。
有 vercel 应该就够了
> ci: remove travis docs trigger

- .github/workflows/test.yml
> ci: use stable node version (v14)

- packages/remax-wechat/src/types/config.ts
如题，在使用过程中，发现针对微信小程序的 app.json TS 声明有误，这里提供修复后的代码
> fix(wechat app.config type fix): 修复微信小程序 app.config.ts 声明错误问题

- docs/guide/basic/plugin.md
修复plugin使用js接口文档可能有问题的点
实际上引用js 的接口的时候，都不是 `plugin://xxx ` 直接是组件名的
> docs: 修复plugin使用js接口文档可能有问题的点

- packages/remax-runtime/src/__tests__/helpers/Page.ts
- packages/remax-runtime/src/createPageConfig.ts
> fix: 修复同一页面的生命周期会重复触发的问题

- packages/remax-cli/src/build/webpack/config.mini.ts
- packages/remax-cli/src/build/webpack/config.web.ts
```js
// remax.config.js
{
plugins: [require('@remax/plugin-less')],
configWebpack({config }){
// 此时无法修改 plugin 的配置
}
}
> fix: 修复 configWebpack 无法修改 plugins 里配置的问题

- packages/remax-cli/src/__tests__/integration/fixtures/createHostComponent/expected/wechat/base.wxml
- packages/remax-cli/src/__tests__/integration/fixtures/one/expected/wechat/base.wxml
- packages/remax-cli/src/__tests__/integration/fixtures/typescript/expected/wechat/base.wxml
- packages/remax-cli/src/__tests__/integration/fixtures/universe/expected/wechat/base.wxml
- packages/remax-cli/src/__tests__/integration/fixtures/wechat/expected/base.wxml
- packages/remax-wechat/templates/children.ejs
[#1369 ](url)
原生小程序是支持给swiper-item 添加class的，有场景可能需要动态操作它的样式
> fix: 修复swiper-item 添加class不生效问题

- e2e/app/package.json
- e2e/plugin/package.json
- package.json
- packages/babel-plugin-remax-host-component/package.json
- packages/babel-plugin-remax-lifecycle/package.json
- packages/babel-plugin-remax-regenerator-runtime/package.json
- packages/babel-plugin-remax-turbo-render/package.json
- packages/babel-preset-remax/package.json
- packages/remax-ali/package.json
- packages/remax-cli/package.json
- packages/remax-framework-shared/package.json
- packages/remax-macro/package.json
- packages/remax-one/package.json
- packages/remax-runtime/package.json
- packages/remax-shared/package.json
- packages/remax-toutiao/package.json
- packages/remax-web/package.json
- packages/remax-wechat/package.json
- packages/remax/package.json
- yarn.lock
**du -sh node_modules**
before|after
-|-
615M|520M
**du -sh packages/*/node_modules | grep M**
before|after
-|-
59M    e2e/app/node_modules|10M    packages/remax-cli/node_modules
59M    e2e/plugin/node_modules|9.2M    packages/remax-macro/node_modules
52M    packages/babel-plugin-remax-host-component/node_modules
52M    packages/babel-plugin-remax-lifecycle/node_modules
52M    packages/babel-plugin-remax-regenerator-runtime/node_modules
52M    packages/babel-plugin-remax-turbo-render/node_modules
9.2M    packages/remax-cli/node_modules
53M    packages/remax-framework-shared/node_modules
9.2M    packages/remax-macro/node_modules
1.5M    packages/remax-shared/node_modules
> build: use consistent typescript/jest version

- .gitignore
- docs/api/remax-cli.md
- docs/api/remax-one/lifecycle.md
- docs/guide/basic/cli.md
- packages/remax-cli/src/builtinPlugins.ts
- packages/remax-cli/src/index.ts
- packages/remax-types/src/index.ts
> fix: 修复 build 模式下未禁用 react-devtools 的问题

- .github/workflows/e2e-web-mpa.yml
- .github/workflows/e2e-web-spa.yml
- .github/workflows/lint.yml
- .github/workflows/mirror.yml
- .github/workflows/test.yml
- docs/guide/one/web.md
- package.json
- packages/babel-preset-remax/package.json
- packages/remax-macro/package.json
- packages/remax-one/package.json
- packages/remax-web/src/index.ts
- yarn.lock
packages
- upgraded `@umijs/babel-plugin-auto-css-modules` for smaller size (ref: https://github.com/umijs/umi/pull/5764)
- fixed `web.md` documentation to match the correct usage
- export types from web
- removed unused `rmc-feedback` dependency
ci
- skip test/lint/e2e actions on docs directory
- ~~`clean:packages` before building is unnecessary (especially in CI)~~
- added [`continue-on-error: true`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error) to make mirror action optional
> chore: touch deps & add continue-on-error to ci

- packages/remax-runtime/src/__tests__/hostConfig/diffProperties.test.ts
- packages/remax-runtime/src/hostConfig/diffProperties.ts
> fix: 修复 style props 变更的错误异常

- packages/remax-wechat/src/__tests__/components/__snapshots__/ScrollView.test.tsx.snap
- packages/remax-wechat/src/hostComponents/ScrollView/index.ts
- packages/remax-wechat/src/hostComponents/ScrollView/node.ts
参考 https://developers.weixin.qq.com/miniprogram/dev/component/scroll-view.html
> fix(wechat): 修复 ScrollView 组件缺失的属性

- packages/remax-wechat/src/hostComponents/Textarea/index.ts
value值改为非必填
[官方文档链接](https://developers.weixin.qq.com/miniprogram/dev/component/textarea.html)
> fix: 修复remax/wechat中textarea的type错误

- docs/guide/config/babel.md
- packages/babel-preset-remax/README.md
- packages/babel-preset-remax/jest.config.js
- packages/babel-preset-remax/package.json
- packages/babel-preset-remax/src/index.test.ts
- packages/babel-preset-remax/src/index.ts
babel-preset-remax 中 preact-react 支持传参 用于支持 可配置是否支持 [New JSX Transform ](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)
使用
```js
{
presets: [
[
'remax',
{
react: {
runtime: 'automatic'
}
},
],
];
}
```
> feat(cli): babel preset-react 参数支持可配置

- packages/remax-cli/src/__tests__/integration/fixtures/hybrid-mini-plugin/expected/pages/mini/index.json
- packages/remax-cli/src/__tests__/integration/fixtures/hybrid-mini-plugin/expected/plugin.json
- packages/remax-cli/src/__tests__/integration/fixtures/hybrid-mini-plugin/src/pages/mini/index.json
- packages/remax-cli/src/__tests__/integration/fixtures/hybrid-mini-plugin/src/plugin.json
- packages/remax-cli/src/build/entries/NativeEntry.ts
错误复现： 当在微信原生文件中的index.json中引用三方plugin时，代码如下
```json
{
"component": true,
"usingComponents": {
"cert": "plugin://wxqmPlugin/cert"
}
}
```
会报下面的错误
增加usingComponents为plugin时的判断（不需要查找相关本地依赖）
[微信plugin文档地址](https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/using.html#%E4%BD%BF%E7%94%A8%E6%8F%92%E4%BB%B6)
> fix(wechat): 引用三方plugin时误报错

- packages/remax-runtime/src/createHostComponent.ts
- packages/remax-runtime/src/createNativeComponent.ts
#1563，添加之后react-devtools会显示host component和小程序原生组件
> fix: #1563使用react-devtools无法显示小程序组件名称

- README.md
> [skip ci] chore: remove outdated travis badge

- packages/remax-web/src/PullToRefresh.tsx
修复web端下拉组件的时候没有初始化Container的高度，导致在子组件中未触底则多次出发问题 #1689
> 修复web端在App/Page生命周期中无法触发小程序生命周期问题

- packages/remax-cli/src/build/webpack/config.mini.ts
当在remax中构建中大型小程序的时候由于babel没有使用cacheDirectory缓存配置，会导致构建asset时间比较久。
> feat(cli): 为babel-loader加入cacheDirectory配置

- packages/remax-runtime/src/Container.ts
- packages/remax-runtime/src/VNode.ts
- packages/remax-runtime/src/__tests__/index.test.tsx
- packages/remax-runtime/src/hostConfig/index.ts
> fix: 修复节点卸载后回调没从 Page 上删除的问题
